services:
  pulsar:
    image: apachepulsar/pulsar:latest
    command: ["bin/pulsar", "standalone"]
    ports:
      - "6650:6650"
      - "8080:8080"
    networks:
      - dapr-pulsar

  publisher:
    build:
      context: ./publisher
      dockerfile: Dockerfile
    depends_on:
      - pulsar
    networks:
      - dapr-pulsar

  publisher-dapr:
    image: "daprio/daprd:edge"
    command: [
      "./daprd",
      "--app-id", "publisher",
      "--app-port", "8890",
      "--app-protocol", "http",
      "--resources-path", "/components",
      "--dapr-grpc-port", "50001",
      "--dapr-http-port", "3500"
    ]
    
    volumes:
      - "./components/:/components"
    depends_on:
      - publisher
    network_mode: "service:publisher"

  subscriber:
    build:
      context: ./subscriber
      dockerfile: Dockerfile
    depends_on:
      - pulsar
    networks:
      - dapr-pulsar

  subscriber-dapr:
    image: "daprio/daprd:edge"
    command: [
      "./daprd",
      "--app-id", "subscriber",
      "--app-port", "8082",
      "--resources-path", "/components",
      "--dapr-grpc-port", "50002",
      "--dapr-http-port", "3501"
    ]
    volumes:
      - "./components/:/components"
    depends_on:
      - subscriber
    network_mode: "service:subscriber"

  # placement:
  #   image: "daprio/dapr"
  #   command: ["./placement", "--port", "50006"]
  #   ports:
  #     - "50006:50006"
  #   networks:
  #     - dapr-pulsar

networks:
  dapr-pulsar:
    driver: bridge
