apiVersion: apps/v1
kind: Deployment
metadata:
  name: publisher
  namespace: pulsar-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: publisher
  template:
    metadata:
      labels:
        app: publisher
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "publisher"
    spec:
      containers:
      - name: publisher
        image: rochabr/publisher:0.4
        imagePullPolicy: Always
        resources:
          requests:
            memory: "512Mi"
            cpu: "0.2"
          limits:
            memory: "1Gi"
            cpu: "0.5"