apiVersion: v1
kind: ConfigMap
metadata:
  name: oauth-credentials-json
  namespace: pulsar-test
data:
  evmg-oauth2-credentials.json: |
    {
      "type": "client_credentials",
      "client_id": "pulsar-client",
      "client_secret": "pulsar-secret",
      "issuer_url": "http://mock-oauth2.pulsar-test.svc.cluster.local:8080/default"
    }
