apiVersion: apps/v1
kind: Deployment
metadata:
  name: publisher
  namespace: pulsar-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: publisher
  template:
    metadata:
      labels:
        app: publisher
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "publisher"
        dapr.io/log-level: "debug"
        dapr.io/log-as-json: "true"
        dapr.io/enable-api-logging: "true"
    spec:
      containers:
      - name: publisher
        image: us-central1-docker.pkg.dev/strong-harbor-338418/elia-sb-debug-mirel/pulsar-bug:latest
        imagePullPolicy: Always