apiVersion: apps/v1
kind: Deployment
metadata:
  name: publisher-fixed-json
  namespace: pulsar-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: publisher-fixed-json
  template:
    metadata:
      labels:
        app: publisher-fixed-json
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "publisher-fixed-json"
        dapr.io/log-level: "debug"
        dapr.io/volume-mounts: "oauth-credentials-json:/snp/resources"
    spec:
      volumes:
        - name: oauth-credentials-json
          configMap:
            name: oauth-credentials-json
      containers:
      - name: publisher
        image: us-central1-docker.pkg.dev/strong-harbor-338418/elia-sb-debug-mirel/pulsar-bug:latest
        imagePullPolicy: Never
        volumeMounts:
          - name: oauth-credentials-json
            mountPath: /snp/resources
            readOnly: true
