apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pulsar-pubsub
  namespace: pulsar-test
spec:
  type: pubsub.pulsar
  version: v1
  metadata:
  - name: host
    value: "pulsar-proxy.pulsar.svc.cluster.local:6650"
  - name: tenant
    value: "public"
  - name: namespace
    value: "default"
  - name: subscribeType
    value: "key_shared"
  - name: processMode
    value: "sync"
  - name: oauth2TokenURL
    value: "http://dex.dex.svc.cluster.local:5556/dex/token"
  - name: oauth2ClientID
    value: "pulsar-client"
  - name: oauth2ClientSecret
    value: "pulsar-secret"
  - name: oauth2Audiences
    value: "pulsar-client"
  - name: oauth2Scopes
    value: "openid"