volumes:
  persistence: false

## disable monitoring stack
victoria-metrics-k8s-stack:
  enabled: false
  prometheusOperator:
    enabled: false
  grafana:
    enabled: false
  alertmanager:
    enabled: false
  prometheus:
    enabled: false

# disabled AntiAffinity
affinity:
  anti_affinity: false

components:
  broker: true          
  proxy: false
  toolset: false        
  autorecovery: false
  pulsar_manager: false
  functions: false

zookeeper:
  replicaCount: 1
  podMonitor:
    enabled: false


bookkeeper:
  replicaCount: 1
  configData:
    dbStorage_writeCacheMaxSizeMb: "32"
    dbStorage_readAheadCacheMaxSizeMb: "32"
    dbStorage_rocksDB_writeBufferSizeMB: "8"
    dbStorage_rocksDB_blockCacheSize: "8388608"
  podMonitor:
    enabled: false

broker:
  replicaCount: 1
  configData:
    autoSkipNonRecoverableData: "true"
    managedLedgerDefaultEnsembleSize: "1"
    managedLedgerDefaultWriteQuorum: "1"
    managedLedgerDefaultAckQuorum: "1"
    brokerClientAuthenticationPlugin: org.apache.pulsar.client.impl.auth.oauth2.AuthenticationOAuth2
    brokerClientAuthenticationParameters: >-
      {"privateKey":"data:application/json;base64,eyJ0eXBlIjoiY2xpZW50X2NyZWRlbnRpYWxzIiwiY2xpZW50X2lkIjoicHVsc2FyLWJyb2tlciIsImNsaWVudF9zZWNyZXQiOiJicm9rZXItc2VjcmV0IiwiaXNzdWVyVXJsIjoiaHR0cDovL21vY2stb2F1dGgyLnB1bHNhci10ZXN0LnN2Yy5jbHVzdGVyLmxvY2FsOjgwODAvZGVmYXVsdCJ9","audience":"pulsar","issuerUrl":"http://mock-oauth2.pulsar-test.svc.cluster.local:8080/default"}
  podMonitor:
    enabled: false

proxy:
  replicaCount: 1
  podMonitor:
    enabled: false

autorecovery:
  podMonitor:
    enabled: false

auth:
  authentication:
    enabled: true
    openid:
      enabled: true
      openIDAllowedTokenIssuers: 
        - "http://mock-oauth2.pulsar-test.svc.cluster.local:8080/default"
      openIDAllowedAudiences: 
        - "pulsar"
      openIDRequireIssuersUseHttps: "false"
      openIDAcceptedTimeLeewaySeconds: "0"
  authorization:
    enabled: false