apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pulsar-pubsub
  namespace: pulsar-test
spec:
  type: pubsub.pulsar
  version: v1
  ignoreErrors: false
  metadata:
  - name: host
    value: "pulsar-broker.pulsar.svc.cluster.local:6650"
  - name: tenant
    value: "public"
  - name: namespace
    value: "default"
  - name: oauth2TokenURL
    value: "http://hydra-oauth2-public.pulsar-test.svc.cluster.local:4444/oauth2/token"
  - name: oauth2ClientID
    value: "pulsar-client"
  - name: oauth2ClientSecretPath
    value: "/snp/resources/pulsar-secret.txt"  # Plain text file
  - name: oauth2Audiences
    value: "pulsar"
  - name: oauth2Scopes
    value: "openid"
