apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: declarative-pulsar-sub
spec:
  topic: messages
  pubsubname: pulsar-pubsub
  routes:
    default: /messages
  metadata:
    subscribeType: key_shared
scopes:
- subscriber