apiVersion: apps/v1
kind: Deployment
metadata:
  name: subscriber
  namespace: pulsar-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: subscriber
  template:
    metadata:
      labels:
        app: subscriber
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "subscriber"
        dapr.io/app-port: "8082"
        dapr.io/app-protocol: "http"
    spec:
      containers:
      - name: subscriber
        image: alicejgibbons/subscriber:1.0
        imagePullPolicy: Always
        env:
        - name: SERVER_PORT
          value: "8082"
        ports:
        - containerPort: 8082
        resources:
          requests:
            memory: "512Mi"
            cpu: "0.2"
          limits:
            memory: "1Gi"
            cpu: "0.5"
