apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pulsar-pubsub
spec:
  type: pubsub.pulsar
  version: v1
  metadata:
  - name: host
    value: "pulsar://pulsar:6650" # running using docker-compose
    #value: "localhost:6650"  # running locally
  - name: tenant
    value: "public"
  - name: namespace
    value: "default"
  # - name: subscribeType
  #   value: "key_shared"
  # - name: processMode
  #   value: "sync"
  # - name: "partitionKey"
  #   value: "authoring-event-topic"