apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pulsar-pubsub
spec:
  type: pubsub.pulsar
  version: v1
  metadata:
  - name: host
    value: localhost:6650
  - name: tenant
    value: "public"
  - name: namespace
    value: "default"