apiVersion: dapr.io/v1alpha1
kind: Resiliency
metadata:
  name: pubsub-res
spec:
  policies:
    retries:
      retry3x:
        policy: constant
        duration: 1s
        maxRetries: 3
  targets:
    components:
      pubsub-redis:
        outbound:
          retry: retry3x
        inbound:
          retry: retry3x
scopes:
- publisher

